# Generated by Django 4.0.5 on 2022-06-20 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='joints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('line', models.CharField(max_length=30)),
                ('doctitle', models.CharField(max_length=60)),
                ('isometric', models.CharField(max_length=60)),
                ('category', models.CharField(max_length=20)),
                ('control', models.CharField(max_length=20)),
                ('materialsteel', models.CharField(max_length=30)),
                ('spoolnumber', models.CharField(max_length=30)),
                ('locationweld', models.CharField(max_length=10)),
                ('numberjoint', models.CharField(max_length=10)),
                ('typeweld', models.CharField(max_length=10)),
                ('dinch', models.FloatField()),
                ('wayweld', models.CharField(max_length=30)),
                ('dateweld', models.DateTimeField()),
                ('stamproot1', models.CharField(max_length=10)),
                ('stamproot2', models.CharField(max_length=10)),
                ('stampfilling1', models.CharField(max_length=10)),
                ('stampfilling2', models.CharField(max_length=10)),
                ('diameter1', models.FloatField()),
                ('thickness1', models.FloatField()),
                ('diameter2', models.FloatField()),
                ('thickness2', models.FloatField()),
                ('element1', models.CharField(max_length=30)),
                ('element2', models.CharField(max_length=30)),
                ('material1', models.CharField(max_length=30)),
                ('material2', models.CharField(max_length=30)),
            ],
        ),
    ]
