# Generated by Django 4.0.5 on 2022-06-20 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joints',
            name='conclusion_vik_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='joints',
            name='conclusion_vik_file',
            field=models.FileField(blank=True, null=True, upload_to='conclusion_vik/'),
        ),
        migrations.AddField(
            model_name='joints',
            name='conclusion_vik_number',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='joints',
            name='conclusion_vik_result',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='joints',
            name='stampfilling2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='joints',
            name='stamproot2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
