# Generated by Django 4.0.5 on 2022-06-20 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_joints_conclusion_vik_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='testmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_text', models.CharField(max_length=30)),
                ('test_date', models.DateTimeField()),
                ('test_file', models.FileField(blank=True, null=True, upload_to='conclusion_vik/')),
            ],
        ),
    ]
