# Generated by Django 4.0.5 on 2022-06-20 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_testmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joints',
            name='material1',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='joints',
            name='material2',
            field=models.CharField(max_length=60),
        ),
    ]
