# Generated by Django 4.0.5 on 2022-06-20 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0004_alter_joints_material1_alter_joints_material2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joints',
            name='element1',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='joints',
            name='element2',
            field=models.CharField(max_length=60),
        ),
    ]
