# Generated by Django 4.0.5 on 2022-06-20 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0005_alter_joints_element1_alter_joints_element2'),
    ]

    operations = [
        migrations.CreateModel(
            name='joint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Титул')),
                ('line', models.CharField(max_length=30, verbose_name='Линия')),
                ('doctitle', models.CharField(max_length=60, verbose_name='Номер чертежа')),
                ('isometric', models.CharField(max_length=60, verbose_name='Изометрия')),
                ('category', models.CharField(max_length=20)),
                ('control', models.CharField(max_length=20)),
                ('materialsteel', models.CharField(max_length=30)),
                ('spoolnumber', models.CharField(max_length=30)),
                ('locationweld', models.CharField(max_length=10, verbose_name='Место сварки')),
                ('numberjoint', models.CharField(max_length=10, verbose_name='Номер стыка')),
                ('typeweld', models.CharField(max_length=10)),
                ('dinch', models.FloatField()),
                ('wayweld', models.CharField(max_length=30)),
                ('dateweld', models.DateTimeField(verbose_name='Дата сварки')),
                ('stamproot1', models.CharField(max_length=10)),
                ('stamproot2', models.CharField(blank=True, max_length=10, null=True)),
                ('stampfilling1', models.CharField(max_length=10)),
                ('stampfilling2', models.CharField(blank=True, max_length=10, null=True)),
                ('diameter1', models.FloatField()),
                ('thickness1', models.FloatField()),
                ('diameter2', models.FloatField()),
                ('thickness2', models.FloatField()),
                ('element1', models.CharField(max_length=60)),
                ('element2', models.CharField(max_length=60)),
                ('material1', models.CharField(max_length=60)),
                ('material2', models.CharField(max_length=60)),
                ('conclusion_vik_date', models.DateTimeField(blank=True, null=True)),
                ('conclusion_vik_result', models.CharField(blank=True, max_length=2, null=True)),
                ('conclusion_vik_number', models.CharField(blank=True, max_length=80, null=True)),
                ('conclusion_vik_file', models.FileField(blank=True, null=True, upload_to='conclusion_vik/')),
            ],
            options={
                'verbose_name': 'Сварные стыки',
                'verbose_name_plural': 'Сварочный журнал',
                'ordering': ['-dateweld'],
            },
        ),
        migrations.DeleteModel(
            name='joints',
        ),
    ]
